/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pa3;

import pa3.one.BirthdayPresents;
import pa3.two.Temp;

public class App {
    public static void main(String[] args) {
        BirthdayPresents app = new BirthdayPresents();
        app.run();
        // Temp t = new Temp();
        // t.run();
    }
}
